# Generated by Django 6.0.3 on 2026-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_completo', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('construtor_id', models.CharField(max_length=100, unique=True)),
                ('campeonatos', models.IntegerField(default=0)),
                ('entrada', models.IntegerField(blank=True, null=True)),
                ('atividade', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
