# Generated by Django 6.0.3 on 2026-04-02 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('piloto_id', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('atividade', models.BooleanField(default=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilotos', to='times.time')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Piloto_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.IntegerField()),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('pontos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('poles', models.IntegerField(default=0)),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='pilotos.piloto')),
            ],
            options={
                'ordering': ['-temporada'],
                'unique_together': {('piloto', 'temporada')},
            },
        ),
    ]
